### ISSUE TITLE
Switch to different api?

### ISSUE THREAD

**Issue by CreeperPlanet26** [swiftnite/Fortnite-Shop-Sections-Bot#4]
FN-API shut down so this app doesn't work anymore? do u know any other APIs that would work as an alternative?
![image](https://user-images.githubusercontent.com/51346607/213047549-631313b3-c1bd-4fb9-81bd-ec9ded7bbc1d.png)

**Comment by swiftnite** [comment]
Hey, the latest version disabled the use of fn-api.com as it was shut down
The only API enabled for use in the latest release is nitestats

**Comment by swiftnite** [comment]
I think I can close this issue. Given it has already been fixed

**Comment by CreeperPlanet26** [comment]
Does this API still update at 5 PM EST? Or is it only at 7

**Comment by swiftnite** [comment]
The bot detects the sections as soon as they come out… it is not time based.

**Comment by CreeperPlanet26** [comment]
What I mean is that does the nitestats API update only when the new item shop is added (8 pm est) or does it update at 5 pm est when epic adds the new shop sections

**Comment by swiftnite** [comment]
It is not time based. The sections come out whenever epic add them. Could be any time.

**Comment by CreeperPlanet26** [comment]
ik what u mean but does nitestats actually update them as they are added. i noticed that nitestats only updates their api at 7:15 EST for the shop sections instead of 5:00 PM EST when epic actually adds them to the api

**Comment by swiftnite** [comment]
Yes it updates as soon as epic update the sections…

**Comment by CreeperPlanet26** [comment]
Interesting. I'm using the same nitestats endpoint and the section store ends array is only changed at 7:15 PM EST instead of a few hours before when epic actually updates them

**Comment by xdFNLeaks** [comment]
> Interesting. I'm using the same nitestats endpoint and the section store ends array is only changed at 7:15 PM EST instead of a few hours before when epic actually updates them

Are you keeping your bot running 24/7? Or have you modified the main code?

**Comment by CreeperPlanet26** [comment]
I have it running all the time and I fetch the data every 15 seconds. If that array is different then I consider that new data but is only changing at 7:15 and not 5:00

**Comment by xdFNLeaks** [comment]
> I have it running all the time and I fetch the data every 15 seconds. If that array is different then I consider that new data but is only changing at 7:15 and not 5:00

Have you modified anything in the main code that may change what the bot is trying to do?

**Comment by CreeperPlanet26** [comment]
Not much. The core logic of looping over and fetching nitestats and checking a cache still exists. Only problem is that nitestats is being updated pretty late

**Comment by xdFNLeaks** [comment]
> Not much. The core logic of looping over and fetching nitestats and checking a cache still exists. Only problem is that nitestats is being updated pretty late 

I'm not sure if it is Nitestats being updated late. It seems to work fine for others, maybe your modifications effected that.

**Comment by CreeperPlanet26** [comment]
maybe. I tried looking at the API in chrome at 5:30 EST and it still showed old shop sections which makes me so confused

**Comment by CreeperPlanet26** [comment]
is the API caching or something. And it's the store section ends array that has the newest sections right?

**Comment by xdFNLeaks** [comment]
Please re-download the repository and try again, **please only modify config.py** unless you know what you are doing, **you shouldn't have to modify the main code**. Let us know if your still having issues.

**Comment by CreeperPlanet26** [comment]
Just modifying to generate an image alongside. Again I went into chrome browser and at 5:00 Est the API was showing old shop sections and it took till 7:15 Est for it to be updated to the current shop sections
